name: sync-branches-dispatch

on:
  push:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      from:
        description: 'from (e.g feature branch)'     
        required: true
        default: ''
      to:
        description: 'to (e.g release branch)'
        required: true
        default: ''

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Opening pull request
        id: pull
        continue-on-error: true
        uses: tretuna/sync-branches@1.4.0
        with:
          CONTENT_COMPARISON: true
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: ${{ github.event.inputs.from }}
          TO_BRANCH: ${{ github.event.inputs.to }}
